spring:
 
  datasource: 
    url: jdbc:mysql://uukasufk9aujrcd0:U9FU32MRZA1Mhoin8DJq@bwmtfujbp33jjfn7fovw-mysql.services.clever-cloud.com:3306/bwmtfujbp33jjfn7fovw
    username: uukasufk9aujrcd0
    password: U9FU32MRZA1Mhoin8DJq
    driver-class-name: com.mysql.cj.jdbc.Driver 
  jpa: 
    show-sql: false
    hibernate:
      ddl-auto: update 
  thymeleaf:
    cache: false
server:
  port: 8080

